const mongoose = require('mongoose');

module.exports = mongoose.model('accidentForm', {
    firstName: String,
    lastName: String,
    address1: String,
    address2: String,
    city: String,
    state: String,
    zip: String,
    homePhone: String,
    workPhone: String,
    ssn: String,
    locationfOfIncident: String,
    department: String,
    division: String,
    position: String,
    supervisor: String,
    dateOfIncident: String,
    timeOfIncident: String,
    locationOfIncidentAddress1: String,
    locationOfIncidentAddress2: String,
    locationOfIncidentCity: String,
    locationOfIncidentState: String,
    locationOfIncidentZip: String,
    policeInvolved: String,
    policeInvolvedInfo: String,
    photosTaken: String,
    paramedicsCalled: String,
    injuredEmployees: String,
    natureInjury: String,
    injuryDetail: String,
    witness: String,
    vehicleTypeUnitNumber: String,
    damageAmount: String,
    otherVehicleMake: String,
    otherVehicleModel: String,
    otherVehicleYear: String,
    otherVehicleLicensePlate: String,
    policeDriverTicketed: String,
    policeDriverInformation: String
}); 
