const mongoose = require('mongoose');

module.exports = mongoose.model('cosumnesReturnToWork', {
    firstName: String,
    lastName: String,
    address1: String,
    address2: String,
    city: String,
    state: String,
    zip: String,
    homePhone: String,
    workPhone: String,
    ssn: String,
    physicianName: String,
    physicianAddress: String,
    dateSigned: String,
    q1: String,
    q2: String,
    q3: String,
    q4: String,
    q5: String,
    q6: String,
    q7: String,
    q8: String,
    q9: String,
    q10: String,
    q11: String,
    q12: String,
    q13: String,
    q14: String,
    q15: String,
    detailRestriction: String,
    q16: String
}); 
